version: '3.1'

services:
  postgres:
    container_name: ecommerce_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - ecommerce_net

networks:
  ecommerce_net: